// languages.ts
export const languages = [
  { code: "en-us", name: "English (United States)" },
  { code: "MatchOS", name: "Match Operating System" },
  { code: "ar-sa", name: "Arabic (Saudi Arabia)" },
  { code: "bg-bg", name: "Bulgarian" },
  { code: "zh-cn", name: "Chinese (Simplified)" },
  { code: "zh-tw", name: "Chinese (Traditional)" },
  { code: "hr-hr", name: "Croatian" },
  { code: "cs-cz", name: "Czech" },
  { code: "da-dk", name: "Danish" },
  { code: "nl-nl", name: "Dutch" },
  { code: "en-gb", name: "English (United Kingdom)" },
  { code: "et-ee", name: "Estonian" },
  { code: "fi-fi", name: "Finnish" },
  { code: "fr-ca", name: "French (Canada)" },
  { code: "fr-fr", name: "French (France)" },
  { code: "de-de", name: "German" },
  { code: "el-gr", name: "Greek" },
  { code: "he-il", name: "Hebrew" },
  { code: "hi-in", name: "Hindi" },
  { code: "hu-hu", name: "Hungarian" },
  { code: "it-it", name: "Italian" },
  { code: "ja-jp", name: "Japanese" },
  { code: "kk-kz", name: "Kazakh" },
  { code: "ko-kr", name: "Korean" },
  { code: "lv-lv", name: "Latvian" },
  { code: "lt-lt", name: "Lithuanian" },
  { code: "ms-my", name: "Malay" },
  { code: "nb-no", name: "Norwegian (Bokmål)" },
  { code: "pl-pl", name: "Polish" },
  { code: "pt-br", name: "Portuguese (Brazil)" },
  { code: "pt-pt", name: "Portuguese (Portugal)" },
  { code: "ro-ro", name: "Romanian" },
  { code: "ru-ru", name: "Russian" },
  { code: "sr-latn-rs", name: "Serbian (Latin)" },
  { code: "sk-sk", name: "Slovak" },
  { code: "sl-si", name: "Slovenian" },
  { code: "es-mx", name: "Spanish (Mexico)" },
  { code: "es-es", name: "Spanish (Spain)" },
  { code: "sv-se", name: "Swedish" },
  { code: "th-th", name: "Thai" },
  { code: "tr-tr", name: "Turkish" },
  { code: "uk-ua", name: "Ukrainian" },
  { code: "vi-vn", name: "Vietnamese" },
  { code: "af-za", name: "Afrikaans" },
  { code: "sq-al", name: "Albanian" },
  { code: "am-et", name: "Amharic" },
  { code: "hy-am", name: "Armenian" },
  { code: "as-in", name: "Assamese" },
  { code: "az-latn-az", name: "Azerbaijani (Latin)" },
  { code: "eu-es", name: "Basque" },
  { code: "be-by", name: "Belarusian" },
  { code: "bn-bd", name: "Bengali (Bangladesh)" },
  { code: "bn-in", name: "Bengali (India)" },
  { code: "bs-latn-ba", name: "Bosnian (Latin)" },
  { code: "ca-es", name: "Catalan" },
  { code: "prs-af", name: "Dari" },
  { code: "fil-ph", name: "Filipino" },
  { code: "gl-es", name: "Galician" },
  { code: "ka-ge", name: "Georgian" },
  { code: "gu-in", name: "Gujarati" },
  { code: "is-is", name: "Icelandic" },
  { code: "ga-ie", name: "Irish" },
  { code: "kn-in", name: "Kannada" },
  { code: "km-kh", name: "Khmer" },
  { code: "sw-ke", name: "Swahili" },
  { code: "kok-in", name: "Konkani" },
  { code: "ky-kg", name: "Kyrgyz" },
  { code: "lb-lu", name: "Luxembourgish" },
  { code: "mk-mk", name: "Macedonian" },
  { code: "ml-in", name: "Malayalam" },
  { code: "mt-mt", name: "Maltese" },
  { code: "mi-nz", name: "Maori" },
  { code: "mr-in", name: "Marathi" },
];
